# name for the entire pipeline
name: Build BookDepo API
# event triggers!
on: push
# what to do
jobs:
    build: # Its a build job
        name: Build the App # first job of the day
        runs-on: windows-latest
        steps:
            - name: Pull the code
              uses: actions/checkout@v2 # copies code from remote repo to vm (build agent)
            - name: Setup runtime environment
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '3.1.x'           
            - name: Build with dotnet cli
              run: dotnet build
